version: '3.8'

services:
  wp:
    image: wordpress:latest
    container_name: wordpress-app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: userpassword
      # VIRTUAL_HOST: example.com
      # LETSENCRYPT_HOST: example.com
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    container_name: wpcli_app
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: userpassword
    depends_on:
      - db
      - wp

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: pma
  #   restart: unless-stopped
  #   environment:
  #     # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     UPLOAD_LIMIT: 50M
  #     VIRTUAL_HOST: phpmyadmin.example.com
  #     LETSENCRYPT_HOST: phpmyadmin.example.com
  #   expose:
  #     - 8081
  #   links:
  #     - db:db
  db:
    image: mysql:8.0
    container_name: wordpressdb
    restart: unless-stopped
    ports:
      - "3309:3306"
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      # - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: userpassword

volumes:
  db_data:
